
env:
  num_fruit: 10
  num_raven: 9
  num_basket: 2
  num_tree: 4
  tree_names: [ 'cherry', 'apple', 'pear', 'plum']
  seed: 123

agent:
  type: "trained"  # "positive", "negative", "random", "trained"
  batches: 10
  games_per_batch: 20000
  gamma: 1
  one_hot_state: False

dqn:
  lr: 0.0005
  batch_size: 5000
  replay_start_size: 50000
  replay_size: 500000
  hidden_size: [50,20]
  eps:
    strategy: "exponential"  # type of decay: constant, linear, exponential
    start: 1.0
    final: 0.1
    share: 0.9
